# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

 #HODL username
username: "andre" # < TU_USUARIO@hodl.ar

# NOSTR Settings
nostr: # Sin el # adelante
   npub: "npub1l63sf9ktwuchkpmxr6qf573dz2t3alndv2rklze3vlrjyrpfggys8xl886" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Andrea Diaz Correia # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Andrea Díaz Correia # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

 - title: Instagram
   icon: instagram
   url: https://www.instagram.com/andreadiazcorreia/

 - title: Twitter
   icon: twitter
   url: https://twitter.com/AndreaDCorreia
    
 - title: LinkedIn # Este es el nombre del botón
   icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
   url: https://www.linkedin.com/in/andrea-diaz-correia/ # Link a donde redireccionará al hacer click

 - title: Github
   icon: github
   url: https://github.com/AndreaDiazCorreia

# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

# - title: Telegram
#   icon: telegram
#   url: https://t.me/TU-USUARIO
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
